fbdev: mdss_mdp: Remove redefinition of BITS_TO_BYTES() macro
Upstream commit 1ce62f5178e43f ("ocfs2/dlm: move BITS_TO_BYTES() to
bitops.h for wider use") has moved BITS_TO_BYTES() to bitops.h and
now the macro is globally usable. As a result, files that have
BITS_TO_BYTES() macro defined in them, mdss_mdp header for this
instance, has got a redefined macro warning by the compiler.

...

(in include/linux/bitops.h)
..    ..
.. VS ..
..    ..
(in drivers/video/fbdev/msm/mdss_mdp.h)

...

The global macro retains the same functionality and thus we can remove
the duplicate aka redefined macro definition from mdss_mdp.h that fixes
the following warning:

In file included from ../drivers/video/fbdev/msm/mdss_mdp.c:49:
../drivers/video/fbdev/msm/mdss_mdp.h:135:9: warning: 'BITS_TO_BYTES' macro redefined [-Wmacro-redefined]
        ^
../include/linux/bitops.h:16:9: note: previous definition is here
        ^
1 warning generated.
In file included from ../drivers/video/fbdev/msm/mdss_mdp.c:49:
../drivers/video/fbdev/msm/mdss_mdp.h:135:9: warning: 'BITS_TO_BYTES' macro redefined [-Wmacro-redefined]
        ^
../include/linux/bitops.h:16:9: note: previous definition is here
        ^

Fixes: 1ce62f5178e43f ("ocfs2/dlm: move BITS_TO_BYTES() to bitops.h for wider use")
Change-Id: I49d05829820356a6110515af8e25bf10f918eee0
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>